language: java
sudo: false
jdk:
  - openjdk8
cache:  
  directories:  
   - $HOME/.m2  

before_install:
    - git clone --depth 1 https://github.com/kit-sdq/BuildUtilities.git /tmp/BuildUtilities
    - . /tmp/BuildUtilities/travis-ci/setupenvironment.sh
install: true

script: ./mvnw -B clean verify

after_success:
- . /tmp/BuildUtilities/travis-ci/deploy.sh metamodels/asem releng/edu.kit.ipd.sdq.metamodels.asem.updatesite repository kit-sdq updatesite